# Local preview only. GitHub Pages builds the site automatically without this file.
#
#   cd docs && bundle install && bundle exec jekyll serve
#
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "webrick"
